### ISSUE TITLE
demo needed

### ISSUE THREAD

**Issue by QinDong0102** [egladysh/memheap#3]
Hi, is there any demo that demostrate how can trivial API to be used ?

Thanks

**Comment by egladysh** [comment]
Hi! There is the test folder that can give you an idea. Basically, the API is very simple and self-explanatory, I think. It's in the memheap.h header. There are just 3 methods plus the c'tor.
	void* allocate(msize n);
	void free(void* p);
	msize get_free_space() const;

**Comment by QinDong0102** [comment]
Thanks for your kindly reply. In my opinion , we should call heap::heap to apply a huge memory space,then use API
void* allocate(msize n);
void free(void* p);
msize get_free_space() const;
to  allocate small memory space just as malloc/free.
Am i right?

thanks

**Comment by egladysh** [comment]
You are very welcome. There is no need to allocate a really huge memory space in heap::heap(). It will grow automatically when full by allocating new chunks of memory. The est_max_size parameter gives memheap a hint of the largest single allocation size by heap::allocate(), and est_cnt is an estimation on the number of such allocations.

**Comment by egladysh** [comment]
For example, if the expected largest single allocation is 1 MB, and we think there is going to be  about 10 such allocations, we can do something like the following:

memheap::heap myheap{true, 1024*1024, 10}; //thread-safe

**Comment by QinDong0102** [comment]
Got it . Thanks
